config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/list', to: 'buckets#show'
  patch '/buckets/:id', to: 'buckets#accomplish'
  get '/users/:id/all', to: 'users#all', as: :all
  get '/users/:id/accomplished', to: 'users#accomplished', as: :accomplished
  get '/users/:id/unaccomplished', to: 'users#unaccomplished', as: :unaccomplished

  resources :users
  resources :buckets

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :asc)}
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :buckets, dependent: :destroy

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                 BCrypt::Engine.cost
   BCrypt::Password.create(string, cost: cost)
 end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    Bucket.where("user_id = ?", id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end

    def slack_notice_register_bucket(bucket)
      notifier = Slack::Notifier.new "#{ENV['SLACK_WEBHOOK_URL']}", channel: "#bucket_notifier", username: "notifier"
      notifier.ping("新しくBucketが追加されました。\n ユーザー名: " + bucket.user.name + "\nBucket: " + bucket.content)
    end

    def slack_notice_register_user(user)
      notifier = Slack::Notifier.new "#{ENV['SLACK_WEBHOOK_URL']}", channel: "#bucket_notifier", username: "notifier"
      notifier.ping("新規ユーザー登録がありました。\nユーザー名:" + user.name + "\nメールアドレス: "+ @user.email)
    end

end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy, :accomplish]

  def show
    @buckets = Bucket.all.reverse_order.paginate(page: params[:page], :per_page => 50)
  end

  def create
    @bucket = current_user.buckets.build(bucket_params)
    if @bucket.save
      flash[:success] = "新しいリストを登録しました"
      slack_notice_register_bucket @bucket
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @bucket.destroy
    flash[:success] = "Bucketを削除しました"
    redirect_to request.referrer || root_url
  end

  def accomplish
    @bucket.is_accomplished = "ture"
    @bucket.comment = "　→達成済み！"
    if @bucket.save
      redirect_to request.referrer || root_url
    else
      flash[:danger] = "更新に失敗しました"
    end
  end

  private

  def bucket_params
    params.require(:bucket).permit(:content)
  end

  def correct_user
    @bucket = current_user.buckets.find_by(id: params[:id])
    redirect_to root_url if @bucket.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = '無効なメールアドレスもしくはパスワードです。'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @bucket = current_user.buckets.build if logged_in?
      @feed_items = current_user.feed
    end
  end

  def help
  end

  def about
  end

  def Contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @buckets = @user.buckets.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      slack_notice_register_user(@user)
      flash[:success] = "登録完了しました！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールの変更を保存しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def all
    @user = User.find(params[:id])
    @buckets = @user.buckets.paginate(page: params[:page])
    render 'show'
  end

  def accomplished
    @user = User.find(params[:id])
    @buckets = @user.buckets.where(is_accomplished: true).paginate(page: params[:page])
    render 'show'
  end

  def unaccomplished
    @user = User.find(params[:id])
    @buckets = @user.buckets.where(is_accomplished: false).paginate(page: params[:page])
    render 'show'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Bucket Lists"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end


  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:fowarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/buckets/_bucket.html.erb
<li id="bucket-<%= bucket.id %>">
  <% if bucket.is_accomplished %>
    <span class="content"><s><%= bucket.content %></s></span>
    <%= bucket.comment %>
    <% if current_user?(bucket.user)  %>
      <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
      <%= link_to "削除", bucket, method: :delete, data: { confirm: "本当に削除しますか？"} %>
    <% end %>
  <% else %>
    <span class="content"><%= bucket.content %></span>
    <% if current_user?(bucket.user) %>
      <%= link_to "達成", bucket, method: :patch %>
      <%= link_to "削除", bucket, method: :delete, data: { confirm: "本当に削除しますか？"} %>
    <% end %>
  <% end %>
</li>

app/views/buckets/show.html.erb
<h2>みんなのリスト</h2>
<p>総リスト数: <%= @buckets.count %></p>
<ul>
  <% @buckets.each do |bucket| %>
  <li><%= bucket.content %> （<%= link_to "#{bucket.user.name}", user_path(bucket.user.id) %>）</li>
  <% end %>
</ul>
<%= will_paginate @buckets %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "このサイトについて",   about_path %></li>
      <li><%= link_to "お問い合わせ", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "人生でやりたいことリスト100", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "みんなのリスト", list_path %></li>
        <% if logged_in? %>
        <li><%= link_to "マイリスト", root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_bucket_form.html.erb
<%= form_for(@bucket) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "やりたいことを記入してください" %>
  </div>
  <%= f.submit "登録", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %><li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="bucket">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィール", current_user %></span>
<span>やりたいことリスト数 : <%= current_user.buckets.count %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
このサイトは、<%= link_to "@benzenetarou", 'https://twitter.com/benzenetarou' %> が運営しています。
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
お問合わせは、<%= link_to "@benzenetarou", 'https://twitter.com/benzenetarou' %>にリプライでお願いします。
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="bucket_form">
        <%= render 'shared/bucket_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>やりたいことリスト</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>人生でやりたいことリスト100</h1>

    <h2>
      人生でやりたいことリストを登録してみよう
    </h2>

    <%= link_to "新規登録", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

<!-- <%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %> -->
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>プロフィール編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード(確認)" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "変更を保存する", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">変更する</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name, class:'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class:'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class:'form-control' %>

      <%= f.label :password_confirmation, "パスワード(確認)" %>
      <%= f.password_field :password_confirmation, class:'form-control' %>

      <%= f.submit "作成", class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name%>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
      <% if @user.buckets.any? %>
        <h3>やりたいことリスト : <%= @user.buckets.count %></h3>
        <%= link_to "All", all_path %>
        <%= link_to "達成", accomplished_path %>
        <%= link_to "未達成", unaccomplished_path %>
        <ol class="bucket">
          <%= render @buckets %>
        </ol>
      <% end %>
    </div>
</div>